#!/bin/bash
# Create PR script - Creates a GitHub Pull Request with a single commit

set -e

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo "Error: GitHub CLI (gh) is not installed."
    echo "Install it from: https://cli.github.com/"
    exit 1
fi

# Check if we're in a git repository
if ! git rev-parse --is-inside-work-tree &> /dev/null; then
    echo "Error: Not in a git repository."
    exit 1
fi

# Get current branch
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Get the default branch (main or master)
DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
if [ -z "$DEFAULT_BRANCH" ]; then
    DEFAULT_BRANCH="main"
fi

# Check if current branch is the default branch
if [[ "$CURRENT_BRANCH" == "$DEFAULT_BRANCH" || "$CURRENT_BRANCH" == "main" || "$CURRENT_BRANCH" == "master" ]]; then
    echo "Error: You are on the $DEFAULT_BRANCH branch. Please checkout a feature branch."
    exit 1
fi

# Check if there are commits to push
if [ "$(git cherry -v "$DEFAULT_BRANCH" 2>/dev/null | wc -l)" -eq 0 ]; then
    echo "Error: No commits to push. Your branch is up to date with main."
    exit 1
fi

# Get the latest commit message
COMMIT_MESSAGE=$(git log -1 --pretty=%B)

# Push the branch if not already pushed
if ! git ls-remote --heads origin "$CURRENT_BRANCH" &> /dev/null; then
    echo "Pushing branch $CURRENT_BRANCH..."
    git push -u origin "$CURRENT_BRANCH"
fi

# Create the Pull Request
echo "Creating Pull Request..."
gh pr create \
    --base "$DEFAULT_BRANCH" \
    --head "$CURRENT_BRANCH" \
    --title "$COMMIT_MESSAGE" \
    --body "$COMMIT_MESSAGE

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>"

echo "Pull Request created successfully!"
